---

- name: install epel
  yum: name=epel-release

- name: install RPM packages required for galaxy
  yum: name={{item}}
  with_items:
  - gcc
  - git
  - libjpeg
  - make
  - memcached
  - python-devel
  - python-pip
  - python-psycopg2
  - python-setuptools
  - PyYAML
  - python-memcached
  - rabbitmq-server
  - supervisor
  - tmux
  - libtiff-devel
  - libjpeg-devel
  - libzip-devel
  - freetype-devel
  - lcms2-devel
  - libwebp-devel
  - tcl-devel
  - tk-devel

- name: install development tool packages
  yum: name={{item}}
  with_items:
  - npm

- name: install pip packages required for galaxy
  pip: name={{item}}
  with_items:
  - django==1.8.3
  - pexpect
  - decorator
  - django-allauth
  - django-autofixture
  - django-avatar
  - django-bootstrap-form
  - django-celery
  - django-filter
  - django-site-maintenance
  - djangorestframework==3.0.5
  - django-debug-toolbar
  - django-haystack
  - drf-haystack
  - elasticsearch==1.7.0   # Latest version not compatible with django-haystack
  - elasticsearch-dsl
  - markdown==2.4.1 # 2.5 currently has a python 2.6.x incompatibility
  - PyGithub
  - requests
  - requests-oauthlib
  - bleach
  - rst2html5-tools

# the avatars directory needs to be there, otherwise the library
# will complain. It isn't used, as all the avatar info is stored
# in the database

- name: create galaxy_manage group
  group: name=galaxy_manage state=present

- name: configure django-avatars directory
  file: path=/var/www/avatars state=directory mode=0755 owner=apache group=galaxy_manage

- name: add vagrant to galaxy_manage group
  user: name=vagrant append=yes groups=galaxy_manage

- name: create galaxy log directory - development
  file:
      path: "{{ galaxy_log_dir }}"
      state: directory
      mode: 0775
      owner: vagrant
      group: vagrant
