version: "1"
defaults:
  foo: {{ lookup('env', 'foo') }}
  ansible_container_version: {{ lookup('version') }}
  bob: {{ 'blah' | test_filter }}
services:
  django:
    image: python:2.7
    working_dir: /galaxy
    volumes:
      - ${PWD}:/galaxy
      - {{ galaxy_log_dir }}:/galaxy_logs
      - {{ galaxy_config_path }}:/etc/galaxy
    links:
      - postgres
      - elastic
      - memcache
      - rabbit
    ports:
      - "8000:8000"
    command: ['/usr/bin/dumb-init', '/galaxy/ansible/start_development.sh']
    dev_overrides:
      user: django

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD={{ galaxy_postgres_password }}
      - POSTGRES_USER={{ galaxy_postgres_user }}
      - POSTGRES_DB={{ galaxy_postgres_db }} 

  elastic:
    image: elasticsearch:latest

  memcache:
    image: memcached:latest

  rabbit:
    image: rabbitmq
    hostname: rabbit
    environment:
      - RABBITMQ_DEFAULT_USER={{ galaxy_rabbitmq_user }}
      - RABBITMQ_DEFAULT_PASS={{ galaxy_rabbitmq_pass }}
      - RABBITMQ_DEFAULT_VHOST={{ galaxy_rabbitmq_vhost }}

  gulp:
    image: centos:7
    volumes:
      - ${PWD}:/galaxy
    command: ["/bin/true"]
    dev_overrides:
      working_dir: /galaxy
      command: ["gulp"]

registries: {}
