---
- hosts: django
  gather_facts: no
  tasks:
    - name: Update all packages
      apt: upgrade=dist

    - name: Install apt-get packages required for galaxy
      apt: name="{{ item }}" update_cache=yes
      with_items:
      - tmux
      - make
      - vim
   
    - name: Create user django
      user: name=django uid=1000 group=root uid=1000 createuser=no

    - name: Download dumb-init
      get_url:
        url: https://github.com/Yelp/dumb-init/releases/download/v1.1.3/dumb-init_1.1.3_amd64.deb
        dest: /dumb-init_1.1.3_amd64.deb

    - name: Install dumb-init
      command: dpkg -i dumb-init_1.1.3_amd64.deb
      args:
        chdir: /

    - name: Remove package dumb-init
      file: path=/dumb-init_1.1.3_amd64.deb state=absent

    - name: Install python packages
      pip: requirements="/galaxy/requirements.txt"

    - name: Install honcho
      pip: name=honcho

    - name: Create the /etc/galaxy directory
      file: path=/etc/galaxy owner=root group=root mode=2770 state=directory

    - name: Create /galaxy_logs directory
      file: path=/galaxy_logs owner=django group=root mode=0775 state=directory

    - name: Intall galaxy
      command: python ./setup.py develop
      args:
        chdir: /galaxy

    - name: Deploy settings file
      template: src=settings.py.j2 dest=/etc/galaxy/settings.py owner=root group=root mode=0660

    - name: Create the SECRET_KEY file
      command: /usr/bin/python -c "import uuid; file('/etc/galaxy/SECRET_KEY', 'wb').write(uuid.uuid4().hex)" creates=/etc/galaxy/SECRET_KEY

    - name: Adjust SECRET_KEY permissions
      file: path=/etc/galaxy/SECRET_KEY state=file owner=root group=root mode=0660

    - name: Wait for postgresql
      wait_for: host=postgres port=5432 connect_timeout=10

    - name: Perform initial migrations 
      command: galaxy-manage migrate --noinput --fake-initial
      args:
        chdir: /galaxy
    - name: Remove any log files
      command: rm -f *.log
      args:
        chdir: /galaxy_logs

- hosts: gulp
  gather_facts: no
  tasks:
    - name: Install epel
      yum: name=epel-release 

    - name: Install nodejs
      yum: name="{{ item }}"
      with_items:
        - nodejs
        - npm

    - name: Install development tools
      npm: path=/galaxy

    - name: Install gulp globally
      npm: name=gulp global=yes

    - name: Install less globally
      npm: name=less global=yes

